### ISSUE TITLE
Flame nerf!

### ISSUE THREAD

**Issue by caramodflame** [camzz/TwitchBot#12]
Everyone has a stupidly huge amount of flames, so we can either nerf the amount people have, or have the fun things to do cost in the thousands!

At the moment it's 5 flames every 5 minutes... shall we drop it, and adjust everyone's flames accordingly?! Perhaps 5 flames every 10 minutes or so? That works out to 30 flames per hour... which would probably be fair with the current prices I sent over to you for the fun things to buy with flames!

Not sure if that's too harsh, so I'm ofc open to discussion!! :DD

**Comment by camzz** [comment]
Ok cool. Shall I half the flames everyone has at the moment?

**Comment by caramodflame** [comment]
Yeah that sounds good to me! And maybe we have a quick !flamenerf command for this weekend, so we can let everyone know that they've just all been adjusted so they haven't technically lost anything! I'll be sad to be under 1000 now tho xD
