### ISSUE TITLE
Cara-mod?

### ISSUE THREAD

**Issue by caramodflame** [camzz/TwitchBot#13]
Cara can't activate any mod-activated commands, as she's technically not a mod! Is there a way for the bot to recognise her as a mod so she can activate the hungerflames etc if she wants to? :D If not that's no worries (it's not super necessary as there's normally always another mod to activate them, but it would be awesome to have the option if it is possible!)

**Comment by camzz** [comment]
Ah yeah, for now I will hardcode it so her username is always seen as mod, and then I can fix it more in future

**Comment by camzz** [comment]
Quick fix done, hardcoded her username as mod. Will fix that more thoroughly in the future
