### ISSUE TITLE
Campfire Additions

### ISSUE THREAD

**Issue by caramodflame** [camzz/TwitchBot#15]
Perhaps give it a 3-minute cooldown from the last entry for any others to enter. After that the campfire will close and the bot will display a message such as "The campfire is now over! Everyone gained x flames"

And depending on which stage it got to, the x will be different obviously!

Just to show that the campfire is over?

**Comment by caramodflame** [comment]
Could also have a similar message for (probably rare!) cases where we don't reach the first fun line of text! Something like "The campfire was over before it even began! Everyone gained 0 flames"

**Comment by caramodflame** [comment]
Oh! And also in the first line of text (the paragraph the bot gives after a mod goes !campfire) perhaps we could add something like "Costs 10 flames to enter" or something? :D

**Comment by camzz** [comment]
Yep will do :)
