### ISSUE TITLE
trifle can be ended multiple times, gives trifle

### ISSUE THREAD

**Issue by caramodflame** [camzz/TwitchBot#16]
RickyB731 : !trifle end
 Moderator CaraBotFlame : weeturtle has eaten the trifle!
weeturtle : Yayy
 Moderator RickyB731 : !trifle end
 Moderator CaraBotFlame : rickyb731 has eaten the trifle!
 Moderator RickyB731 : !trifle end
 Moderator CaraBotFlame : There are no entrants in the trifle

^transcript as example

**Comment by camzz** [comment]
Thats intentional, its based on the raffle code so if someone is around to claim their trifle, you can redraw to get another.

Can you think of a better way to do it? I was just relying on mods to only pull it once if its only needed once. Does that make sense?
