### ISSUE TITLE
campfire

### ISSUE THREAD

**Issue by camzz** [camzz/TwitchBot#4]
Users can start a campfire, at small cost.
More users add to the campfire until it burns bright.
If enough users add within the time limit everyone gets a reward.

**Comment by caramodflame** [comment]
Shannyyyy here! More campfire details for you camz :D 

Start with !campfire or something similar, mod-only start as well 
Bot comes back with a message of something like "Let's all build a campfire together! Everyone start gathering some sticks, and soon we'll be able to toast marshmallows and tell ghost stories! Enter with !fire."

After 5 people have entered, another message: "Great job, everyone! Now, someone find some matches and let's see if we can get this fire started" (Rewards 5 flames at this point if no-one else enters)

After 8 people: "We're starting to see some embers... Keep going!" (Rewards 8 flames at this point if no-one else enters)

After 10 people: "Amazing work -- the fire is stable! Just a few more people and we can start making some delicious food!" (Rewards 15 flames at this point if no-one else enters) 

After 15 people: "Excellent job. There's enough s'mores and toasted marshmallows for everyone! The strim campfire was a raging success!" (Rewards 20 flames at this point if no-one else enters) 

After 20 people: "You managed to keep the campfire going all night! Wonderful!" (Rewards a randomly rolled number of flames to each individual, between 20 and 50). Will also need a message of "@username for all your hard-work in keeping the campfire going, you have earned x flames"

How does that look?! :D

**Comment by camzz** [comment]
Sounds good, will get on it :)
